package main

import (
	"flag"
	"fmt"
	"os"
	"os/exec"
	"os/user"
	"path/filepath"
	"strings"
)

// serviceCmd installs ModelFabric as a systemd service for headless operation, the
// equivalent of running llmster under systemctl.
// systemdArg quotes a path for a systemd ExecStart line. systemd applies its
// own quoting rules and expands "%" specifiers, so a path containing a space,
// a quote, a backslash or a percent sign would otherwise change what is run.
func systemdArg(p string) string {
	q := strings.NewReplacer(`\`, `\\`, `"`, `\"`, "%", "%%").Replace(p)
	return `"` + q + `"`
}

func serviceCmd(args []string) error {
	if len(args) == 0 || (args[0] != "install" && args[0] != "unit") {
		return fmt.Errorf("usage: mfsh service install [-dir DIR] [-enable]\n       mfsh service unit      print the unit to stdout (e.g. for a system-wide install)")
	}
	// ContinueOnError so a bad flag returns through this function's error,
	// the way every other subcommand reports one, instead of calling os.Exit
	// from inside a function that promises to return.
	fs := flag.NewFlagSet("service", flag.ContinueOnError)
	cfgPath := fs.String("config", defaultConfigPath(), "config file the service runs with")
	home, err := os.UserHomeDir()
	if err != nil {
		// The unit file's paths are absolute by necessity: systemd runs from
		// "/", so an empty home turned the install directory into a relative
		// path that resolves somewhere else entirely.
		return fmt.Errorf("cannot determine the home directory: %w", err)
	}
	dir := fs.String("dir", filepath.Join(home, ".config", "systemd", "user"), "where to write the unit")
	enable := fs.Bool("enable", false, "enable and start it now (systemctl --user enable --now)")
	if err := fs.Parse(args[1:]); err != nil {
		return err
	}

	self, err := os.Executable()
	if err != nil {
		return err
	}
	// Resolving is a nicety, not a requirement: if the path cannot be resolved
	// (it was replaced, or a parent is unreadable) the original absolute path
	// is still correct, while the discarded error left `self` empty.
	if resolved, err := filepath.EvalSymlinks(self); err == nil {
		self = resolved
	}
	unit := serviceUnit(self, *cfgPath)

	if args[0] == "unit" {
		fmt.Print(unit)
		return nil
	}
	if err := os.MkdirAll(*dir, 0o755); err != nil {
		return err
	}
	// A unit from before the project was renamed runs the old llmz binary on
	// the same port. Enabling this one beside it would leave two services
	// fighting for :1234, and systemd restarting whichever lost.
	// Only a unit that is enabled or running is in the way; a disabled one is
	// just a stale file.
	if old := filepath.Join(*dir, "llmz.service"); *enable {
		if _, err := os.Stat(old); err == nil {
			for _, check := range []string{"is-enabled", "is-active"} {
				if exec.Command("systemctl", "--user", check, "--quiet", "llmz").Run() == nil {
					return fmt.Errorf("%s from before the rename is still %s; stop it first:\n  systemctl --user disable --now llmz && rm %s",
						old, strings.TrimPrefix(check, "is-"), old)
				}
			}
		}
	}
	path := filepath.Join(*dir, "mfsh.service")
	if err := os.WriteFile(path, []byte(unit), 0o644); err != nil {
		return err
	}
	fmt.Printf("%s %s\n", green("✓ wrote"), path)

	if !*enable {
		fmt.Printf("\n  Start it, and on every login:\n    %s\n", bold("systemctl --user daemon-reload && systemctl --user enable --now mfsh"))
	} else {
		for _, a := range [][]string{{"--user", "daemon-reload"}, {"--user", "enable", "--now", "mfsh"}} {
			if out, err := exec.Command("systemctl", a...).CombinedOutput(); err != nil {
				return fmt.Errorf("systemctl %s: %v\n%s", strings.Join(a, " "), err, out)
			}
		}
		fmt.Printf("%s mfsh.service is enabled and running\n", green("✓"))
	}

	// A user service stops when its user logs out — the classic surprise on a
	// headless machine. Linger keeps it running with nobody logged in.
	if u, err := user.Current(); err == nil {
		if _, err := os.Stat("/var/lib/systemd/linger/" + u.Username); err != nil {
			fmt.Printf("\n  %s it will stop when you log out. To keep it running headless:\n    %s\n",
				yellow("Note:"), bold("loginctl enable-linger "+u.Username))
		}
	}
	return nil
}

func serviceUnit(bin, cfgPath string) string {
	return fmt.Sprintf(`# Generated by ModelFabric (mfsh service install).
[Unit]
Description=ModelFabric model mesh node
Documentation=https://github.com/gregbugaj/modelfabric
Wants=network-online.target
After=network-online.target

[Service]
Type=simple
ExecStart=%s serve%s
Restart=on-failure
RestartSec=3
# Signal only ModelFabric and let it unload its engines in order; the default
# control-group mode would kill every engine at the same instant.
KillMode=mixed
# Unloading a large model can take a while; give it time before SIGKILL.
TimeoutStopSec=90
# Engines are GPU processes; do not let the OOM killer pick ModelFabric first.
OOMScoreAdjust=-100

[Install]
WantedBy=default.target
`, systemdArg(bin), configArg(cfgPath))
}

// configArg is the unit's -config, or nothing for the default path: a unit
// outlives the build that wrote it, and a default frozen into it is the path
// that build had, not the one the next build reads.
func configArg(cfgPath string) string {
	if cfgPath == "" || cfgPath == defaultConfigPath() {
		return ""
	}
	return " -config " + systemdArg(cfgPath)
}
