package main

import (
	"flag"
	"fmt"
	"os"
	"os/exec"
	"os/user"
	"path/filepath"
	"strings"
)

// systemdArg quotes a path for ExecStart. Escape systemd quoting characters
// and percent specifiers so paths do not change the executed command.
func systemdArg(p string) string {
	q := strings.NewReplacer(`\`, `\\`, `"`, `\"`, "%", "%%").Replace(p)
	return `"` + q + `"`
}

func serviceCmd(args []string) error {
	if len(args) == 0 || (args[0] != "install" && args[0] != "unit") {
		return fmt.Errorf("usage: mfsh service install [-dir DIR] [-enable]\n       mfsh service unit      print the unit to stdout (e.g. for a system-wide install)")
	}
	fs := flag.NewFlagSet("service", flag.ContinueOnError)
	cfgPath := fs.String("config", defaultConfigPath(), "config file the service runs with")
	home, err := os.UserHomeDir()
	if err != nil {
		// Require an absolute home path because systemd runs from /.
		return fmt.Errorf("cannot determine the home directory: %w", err)
	}
	dir := fs.String("dir", filepath.Join(home, ".config", "systemd", "user"), "where to write the unit")
	enable := fs.Bool("enable", false, "enable and start it now (systemctl --user enable --now)")
	if err := fs.Parse(args[1:]); err != nil {
		return err
	}

	self, err := os.Executable()
	if err != nil {
		return err
	}
	if resolved, err := filepath.EvalSymlinks(self); err == nil {
		self = resolved
	}
	unit := serviceUnit(self, *cfgPath)

	if args[0] == "unit" {
		fmt.Print(unit)
		return nil
	}
	if err := os.MkdirAll(*dir, 0o755); err != nil {
		return err
	}
	// Reject an enabled or running legacy unit to avoid competing services on the same port.
	if old := filepath.Join(*dir, "llmz.service"); *enable {
		if _, err := os.Stat(old); err == nil {
			for _, check := range []string{"is-enabled", "is-active"} {
				if exec.Command("systemctl", "--user", check, "--quiet", "llmz").Run() == nil {
					return fmt.Errorf("%s from before the rename is still %s; stop it first:\n  systemctl --user disable --now llmz && rm %s",
						old, strings.TrimPrefix(check, "is-"), old)
				}
			}
		}
	}
	path := filepath.Join(*dir, "mfsh.service")
	if err := os.WriteFile(path, []byte(unit), 0o644); err != nil {
		return err
	}
	fmt.Printf("%s %s\n", green("✓ wrote"), path)

	if !*enable {
		fmt.Printf("\n  Start it, and on every login:\n    %s\n", bold("systemctl --user daemon-reload && systemctl --user enable --now mfsh"))
	} else {
		for _, a := range [][]string{{"--user", "daemon-reload"}, {"--user", "enable", "--now", "mfsh"}} {
			if out, err := exec.Command("systemctl", a...).CombinedOutput(); err != nil {
				return fmt.Errorf("systemctl %s: %v\n%s", strings.Join(a, " "), err, out)
			}
		}
		fmt.Printf("%s mfsh.service is enabled and running\n", green("✓"))
	}

	// Linger keeps the user service running after logout.
	if u, err := user.Current(); err == nil {
		if _, err := os.Stat("/var/lib/systemd/linger/" + u.Username); err != nil {
			fmt.Printf("\n  %s it will stop when you log out. To keep it running headless:\n    %s\n",
				yellow("Note:"), bold("loginctl enable-linger "+u.Username))
		}
	}
	return nil
}

func serviceUnit(bin, cfgPath string) string {
	return fmt.Sprintf(`# Generated by ModelFabric (mfsh service install).
[Unit]
Description=ModelFabric model mesh node
Documentation=https://github.com/gregbugaj/modelfabric
Wants=network-online.target
After=network-online.target

[Service]
Type=simple
ExecStart=%s serve%s
Restart=on-failure
RestartSec=3
# Signal only ModelFabric and let it unload its engines in order; the default
# control-group mode would kill every engine at the same instant.
KillMode=mixed
# Unloading a large model can take a while; give it time before SIGKILL.
TimeoutStopSec=90
# Engines are GPU processes; do not let the OOM killer pick ModelFabric first.
OOMScoreAdjust=-100

[Install]
WantedBy=default.target
`, systemdArg(bin), configArg(cfgPath))
}

// configArg omits the default config path so installed units follow future default changes.
func configArg(cfgPath string) string {
	if cfgPath == "" || cfgPath == defaultConfigPath() {
		return ""
	}
	return " -config " + systemdArg(cfgPath)
}
