// Package discovery exports mesh endpoints through llm-d's watched YAML file
// interface, avoiding a dependency on its Go plugin.
//
//	endpoints:
//	  - name: <string>        # required, unique within the file
//	    namespace: <string>   # optional, defaults to "default"
//	    address: <IPv4>       # required, must be IPv4
//	    port: "<1-65535>"     # required, a string
//	    labels: {k: v}        # optional
package discovery

import (
	"fmt"
	"net"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

type Endpoint struct {
	Name      string
	Namespace string
	Address   string
	// Port is what llm-d dials and scrapes. Where ModelFabric republishes an
	// engine's metrics through the shim, that is the shim's port, not the
	// engine's; the EPP scrapes whatever it routes to (see engineshim).
	Port   int
	Labels map[string]string

	// EnginePort is the engine's own OpenAI port, when it differs from Port.
	// Anything that talks inference rather than metrics wants this one: the
	// shim's port is the one llm-d dials and scrapes.
	EnginePort int
}

// Validate enforces the plugin's constraints before we write a file the EPP
// would reject wholesale.
func (e Endpoint) Validate() error {
	if e.Name == "" {
		return fmt.Errorf("endpoint has no name")
	}
	if e.Port < 1 || e.Port > 65535 {
		return fmt.Errorf("endpoint %s: port %d out of range", e.Name, e.Port)
	}
	ip := net.ParseIP(e.Address)
	if ip == nil {
		return fmt.Errorf("endpoint %s: %q is not an IP address", e.Name, e.Address)
	}
	// The standard file-discovery plugin is IPv4-only. A tailnet advertises
	// both families, so this is a live constraint rather than a formality.
	if ip.To4() == nil {
		return fmt.Errorf("endpoint %s: %s is IPv6; llm-d file discovery accepts IPv4 only",
			e.Name, e.Address)
	}
	return nil
}

// Unreachable reports whether an endpoint is bound to loopback while being
// advertised to a scheduler that may run elsewhere.
//
// This is the trap in exporting a ModelFabric mesh: engines bind 127.0.0.1 by
// default, which is correct for ModelFabric's own routing (it proxies via peers) but
// useless to an external EPP, which dials the address directly.
func (e Endpoint) Unreachable() bool {
	ip := net.ParseIP(e.Address)
	return ip != nil && ip.IsLoopback()
}

// NeedsRewrite reports whether reaching this engine means changing the
// request's "model" field, which only ModelFabric itself does. Such an engine is
// reached through its own node, never dialled directly; an engine that
// dispatches on the model id answers an unrecognised one by trying to download
// it, or by failing.
func (e Endpoint) NeedsRewrite() bool {
	served := e.Labels[ServedModelLabel]
	// "modelfabric.sh/model" is spelled out rather than imported: internal/llmd
	// owns that constant and imports this package.
	return served != "" && served != e.Labels["modelfabric.sh/model"]
}

// Render writes the llm-d endpoints file contents.
//
// Endpoints are sorted by name so the output is stable: an unstable file would
// retrigger the EPP's fsnotify watch on every write for no reason.
func Render(endpoints []Endpoint) ([]byte, error) {
	sorted := append([]Endpoint(nil), endpoints...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Name < sorted[j].Name })

	var b strings.Builder
	b.WriteString("# Generated by ModelFabric. Do not edit; changes are overwritten.\n")
	b.WriteString("# Consumed by llm-d's file-discovery plugin:\n")
	b.WriteString("#   plugins:\n")
	b.WriteString("#     - type: file-discovery\n")
	b.WriteString("#       name: file-discovery\n")
	b.WriteString("#       parameters: {path: <this file>, watchFile: true}\n")
	b.WriteString("#   dataLayer: {discovery: {pluginRef: file-discovery}}\n")
	b.WriteString("endpoints:\n")

	if len(sorted) == 0 {
		b.WriteString("  []\n")
		return []byte(b.String()), nil
	}

	seen := make(map[string]bool, len(sorted))
	for _, e := range sorted {
		if err := e.Validate(); err != nil {
			return nil, err
		}
		// The file schema requires unique names. Two entries sharing one made
		// a file the EPP reads as a single endpoint, silently dropping the
		// other; a whole engine missing from scheduling with nothing said.
		if seen[e.Name] {
			return nil, fmt.Errorf("two endpoints are both named %q", e.Name)
		}
		seen[e.Name] = true
		fmt.Fprintf(&b, "  - name: %s\n", yamlScalar(e.Name))
		ns := e.Namespace
		if ns == "" {
			ns = "default"
		}
		fmt.Fprintf(&b, "    namespace: %s\n", yamlScalar(ns))
		fmt.Fprintf(&b, "    address: %q\n", e.Address)
		fmt.Fprintf(&b, "    port: %q\n", strconv.Itoa(e.Port))
		if len(e.Labels) > 0 {
			keys := make([]string, 0, len(e.Labels))
			for k := range e.Labels {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			b.WriteString("    labels:\n")
			for _, k := range keys {
				fmt.Fprintf(&b, "      %s: %s\n", yamlScalar(k), yamlScalar(e.Labels[k]))
			}
		}
	}
	return []byte(b.String()), nil
}

// yamlScalar quotes a value when it would otherwise be misread. Model keys
// contain '/', '.' and digits, which are fine bare, but quoting anything with
// YAML-significant characters keeps the output unambiguous.
func yamlScalar(s string) string {
	if s == "" {
		return `""`
	}
	// Only an indicator character in the *first* position changes how YAML
	// reads a scalar; '-' or ':' inside a word (as in "inst-8646" or a model
	// key) is ordinary text, so quoting those would only add noise.
	switch s[0] {
	case '-', '?', ':', ',', '[', ']', '{', '}', '#', '&', '*', '!', '|', '>',
		'\'', '"', '%', '@', '`', ' ':
		return strconv.Quote(s)
	}
	// ": " and " #" start a mapping value and a comment anywhere in the line.
	if strings.Contains(s, ": ") || strings.Contains(s, " #") ||
		strings.ContainsAny(s, "\n\t") || strings.HasSuffix(s, ":") {
		return strconv.Quote(s)
	}
	// Leading or trailing whitespace is stripped from a plain scalar, so the
	// value read back is not the value written.
	if strings.TrimSpace(s) != s {
		return strconv.Quote(s)
	}
	// A bare scalar that parses as a number or bool must be quoted to stay a string.
	switch strings.ToLower(s) {
	case "true", "false", "null", "yes", "no", "on", "off", "~":
		return strconv.Quote(s)
	}
	if _, err := strconv.ParseFloat(s, 64); err == nil {
		return strconv.Quote(s)
	}
	return s
}

// WriteFile renders and atomically replaces the endpoints file.
//
// It reports whether the contents changed. Rewriting an identical file would
// wake the EPP's watcher for nothing, and the rename keeps a watcher from ever
// observing a half-written list.
func WriteFile(path string, endpoints []Endpoint) (changed bool, err error) {
	data, err := Render(endpoints)
	if err != nil {
		return false, err
	}
	if existing, err := os.ReadFile(path); err == nil && string(existing) == string(data) {
		return false, nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return false, err
	}
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, data, 0o644); err != nil {
		return false, err
	}
	if err := os.Rename(tmp, path); err != nil {
		return false, err
	}
	return true, nil
}
